//
//  Constant.swift
//  CourseWork
//
//  Created by Айрат Туктамышев on 22/05/2019.
//  Copyright © 2019 Айрат Туктамышев. All rights reserved.
//

import UIKit



enum constants
{
    static mykey
}

let mykey="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjI2OTBjM2ZjLWVjZjctNDEyMi1iY2FjLTE0ZDJjMDJlMjJmNiIsImlhdCI6MTU1ODk2MzczOSwic3ViIjoiZGV2ZWxvcGVyLzIwZDQ4ODAwLTkzOTYtNmRmNS0xMGUzLWQxODQ3Njg1OTU1MiIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI0Ni44LjExNy4yNTAiXSwidHlwZSI6ImNsaWVudCJ9XX0.JksLHU4tqNls1KJqf4aEM85creNReBLKTdEoK1btUH3D8gs9ZW1lgyaGrUn_64OX26KP-fx-6JRF3Gnb7VFBfw"
